2025-07-23T14:40:51.21552721Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 236, in run
2025-07-23T14:40:51.21552933Z     super().run()
2025-07-23T14:40:51.21553145Z     ~~~~~~~~~~~^^
2025-07-23T14:40:51.2155338Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 72, in run
2025-07-23T14:40:51.21553578Z     Arbiter(self).run()
2025-07-23T14:40:51.21553781Z     ~~~~~~~^^^^^^
2025-07-23T14:40:51.21553978Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/arbiter.py", line 58, in __init__
2025-07-23T14:40:51.21554177Z     self.setup(app)
2025-07-23T14:40:51.2155437Z     ~~~~~~~~~~^^^^^
2025-07-23T14:40:51.21554586Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/arbiter.py", line 118, in setup
2025-07-23T14:40:51.21554794Z     self.app.wsgi()
2025-07-23T14:40:51.21555Z     ~~~~~~~~~~~~~^^
2025-07-23T14:40:51.215557211Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 67, in wsgi
2025-07-23T14:40:51.215560531Z     self.callable = self.load()
2025-07-23T14:40:51.215562601Z                     ~~~~~~~~~^^
2025-07-23T14:40:51.215564571Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2025-07-23T14:40:51.215566541Z     return self.load_wsgiapp()
2025-07-23T14:40:51.215568541Z            ~~~~~~~~~~~~~~~~~^^
2025-07-23T14:40:51.215571321Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2025-07-23T14:40:51.215576691Z     return util.import_app(self.app_uri)
2025-07-23T14:40:51.215579121Z            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
2025-07-23T14:40:51.215581571Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/util.py", line 371, in import_app
2025-07-23T14:40:51.215583791Z     mod = importlib.import_module(module)
2025-07-23T14:40:51.215586252Z   File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-07-23T14:40:51.215588312Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-07-23T14:40:51.215590352Z            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-23T14:40:51.215592472Z   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-07-23T14:40:51.215594532Z   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-07-23T14:40:51.215596622Z   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2025-07-23T14:40:51.215598822Z   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2025-07-23T14:40:51.215615272Z   File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
2025-07-23T14:40:51.215617812Z   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-07-23T14:40:51.215619762Z   File "/opt/render/project/src/backend/config/wsgi.py", line 16, in <module>
2025-07-23T14:40:51.215621952Z     application = get_wsgi_application()
2025-07-23T14:40:51.215636733Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-07-23T14:40:51.215639143Z     django.setup(set_prefix=False)
2025-07-23T14:40:51.215641703Z     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-07-23T14:40:51.215644043Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-07-23T14:40:51.215646343Z     apps.populate(settings.INSTALLED_APPS)
2025-07-23T14:40:51.215648713Z     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-23T14:40:51.215660803Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/apps/registry.py", line 124, in populate
2025-07-23T14:40:51.215664074Z     app_config.ready()
2025-07-23T14:40:51.215666694Z     ~~~~~~~~~~~~~~~~^^
2025-07-23T14:40:51.215668974Z   File "/opt/render/project/src/backend/ai_service/apps.py", line 11, in ready
2025-07-23T14:40:51.215671074Z     from . import signals
2025-07-23T14:40:51.215673194Z   File "/opt/render/project/src/backend/ai_service/signals.py", line 7, in <module>
2025-07-23T14:40:51.215675324Z     from ai_services.common.signals import ai_usage_logged
2025-07-23T14:40:51.215685214Z ModuleNotFoundError: No module named 'ai_services'
2025-07-23T14:40:52.938725922Z ==> Exited with status 1
2025-07-23T14:40:52.956144Z ==> Common ways to troubleshoot your deploy: https://render.com/docs/troubleshooting-deploys
2025-07-23T14:41:02.204633679Z ==> Running '     gunicorn config.wsgi:client-nest'
2025-07-23T14:41:08.114756632Z /opt/render/project/src/.venv/lib/python3.13/site-packages/drf_yasg/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
2025-07-23T14:41:08.114779063Z   from pkg_resources import DistributionNotFound, get_distribution
2025-07-23T14:41:08.909095789Z Traceback (most recent call last):
2025-07-23T14:41:08.909949761Z   File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
2025-07-23T14:41:08.909960892Z     sys.exit(run())
2025-07-23T14:41:08.909965132Z              ~~~^^
2025-07-23T14:41:08.909972092Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2025-07-23T14:41:08.909976992Z     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2025-07-23T14:41:08.909981322Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
2025-07-23T14:41:08.909985492Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 236, in run
2025-07-23T14:41:08.909990172Z     super().run()
2025-07-23T14:41:08.909994533Z     ~~~~~~~~~~~^^
2025-07-23T14:41:08.910048294Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 72, in run
2025-07-23T14:41:08.910053464Z     Arbiter(self).run()
2025-07-23T14:41:08.910057424Z     ~~~~~~~^^^^^^
2025-07-23T14:41:08.910061504Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/arbiter.py", line 58, in __init__
2025-07-23T14:41:08.910065354Z     self.setup(app)
2025-07-23T14:41:08.910069235Z     ~~~~~~~~~~^^^^^
2025-07-23T14:41:08.910073535Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/arbiter.py", line 118, in setup
2025-07-23T14:41:08.910077995Z     self.app.wsgi()
2025-07-23T14:41:08.910122676Z     ~~~~~~~~~~~~~^^
2025-07-23T14:41:08.910128386Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 67, in wsgi
2025-07-23T14:41:08.910132816Z     self.callable = self.load()
2025-07-23T14:41:08.910137396Z                     ~~~~~~~~~^^
2025-07-23T14:41:08.910141946Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2025-07-23T14:41:08.910146017Z     return self.load_wsgiapp()
2025-07-23T14:41:08.910150386Z            ~~~~~~~~~~~~~~~~~^^
2025-07-23T14:41:08.910154967Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2025-07-23T14:41:08.910159667Z     return util.import_app(self.app_uri)
2025-07-23T14:41:08.910182017Z            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
2025-07-23T14:41:08.910187147Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/util.py", line 371, in import_app
2025-07-23T14:41:08.910191398Z     mod = importlib.import_module(module)
2025-07-23T14:41:08.910196318Z   File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-07-23T14:41:08.910200858Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-07-23T14:41:08.910205098Z            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-23T14:41:08.910209398Z   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-07-23T14:41:08.910213658Z   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-07-23T14:41:08.910217718Z   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2025-07-23T14:41:08.910234389Z   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2025-07-23T14:41:08.910237449Z   File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
2025-07-23T14:41:08.910240509Z   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-07-23T14:41:08.910243429Z   File "/opt/render/project/src/backend/config/wsgi.py", line 16, in <module>
2025-07-23T14:41:08.910246139Z     application = get_wsgi_application()
2025-07-23T14:41:08.910248949Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-07-23T14:41:08.910251669Z     django.setup(set_prefix=False)
2025-07-23T14:41:08.910254209Z     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-07-23T14:41:08.910256929Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-07-23T14:41:08.910259619Z     apps.populate(settings.INSTALLED_APPS)
2025-07-23T14:41:08.910262169Z     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-23T14:41:08.910264749Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/apps/registry.py", line 124, in populate
2025-07-23T14:41:08.91026733Z     app_config.ready()
2025-07-23T14:41:08.91026999Z     ~~~~~~~~~~~~~~~~^^
2025-07-23T14:41:08.91027277Z   File "/opt/render/project/src/backend/ai_service/apps.py", line 11, in ready
2025-07-23T14:41:08.91027615Z     from . import signals
2025-07-23T14:41:08.91027851Z   File "/opt/render/project/src/backend/ai_service/signals.py", line 7, in <module>
2025-07-23T14:41:08.91028135Z     from ai_services.common.signals import ai_usage_logged
2025-07-23T14:41:08.91029277Z ModuleNotFoundError: No module named 'ai_services'
2025-07-23T14:41:02.204633679Z ==> Running '     gunicorn config.wsgi:client-nest'
2025-07-23T14:41:08.114756632Z /opt/render/project/src/.venv/lib/python3.13/site-packages/drf_yasg/__init__.py:2: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
2025-07-23T14:41:08.114779063Z   from pkg_resources import DistributionNotFound, get_distribution
2025-07-23T14:41:08.909095789Z Traceback (most recent call last):
2025-07-23T14:41:08.909949761Z   File "/opt/render/project/src/.venv/bin/gunicorn", line 8, in <module>
2025-07-23T14:41:08.909960892Z     sys.exit(run())
2025-07-23T14:41:08.909965132Z              ~~~^^
2025-07-23T14:41:08.909972092Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
2025-07-23T14:41:08.909976992Z     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
2025-07-23T14:41:08.909981322Z     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
2025-07-23T14:41:08.909985492Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 236, in run
2025-07-23T14:41:08.909990172Z     super().run()
2025-07-23T14:41:08.909994533Z     ~~~~~~~~~~~^^
2025-07-23T14:41:08.910048294Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 72, in run
2025-07-23T14:41:08.910053464Z     Arbiter(self).run()
2025-07-23T14:41:08.910057424Z     ~~~~~~~^^^^^^
2025-07-23T14:41:08.910061504Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/arbiter.py", line 58, in __init__
2025-07-23T14:41:08.910065354Z     self.setup(app)
2025-07-23T14:41:08.910069235Z     ~~~~~~~~~~^^^^^
2025-07-23T14:41:08.910073535Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/arbiter.py", line 118, in setup
2025-07-23T14:41:08.910077995Z     self.app.wsgi()
2025-07-23T14:41:08.910122676Z     ~~~~~~~~~~~~~^^
2025-07-23T14:41:08.910128386Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/base.py", line 67, in wsgi
2025-07-23T14:41:08.910132816Z     self.callable = self.load()
2025-07-23T14:41:08.910137396Z                     ~~~~~~~~~^^
2025-07-23T14:41:08.910141946Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
2025-07-23T14:41:08.910146017Z     return self.load_wsgiapp()
2025-07-23T14:41:08.910150386Z            ~~~~~~~~~~~~~~~~~^^
2025-07-23T14:41:08.910154967Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
2025-07-23T14:41:08.910159667Z     return util.import_app(self.app_uri)
2025-07-23T14:41:08.910182017Z            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
2025-07-23T14:41:08.910187147Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/gunicorn/util.py", line 371, in import_app
2025-07-23T14:41:08.910191398Z     mod = importlib.import_module(module)
2025-07-23T14:41:08.910196318Z   File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
2025-07-23T14:41:08.910200858Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-07-23T14:41:08.910205098Z            ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-23T14:41:08.910209398Z   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
2025-07-23T14:41:08.910213658Z   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
2025-07-23T14:41:08.910217718Z   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
2025-07-23T14:41:08.910234389Z   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
2025-07-23T14:41:08.910237449Z   File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
2025-07-23T14:41:08.910240509Z   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-07-23T14:41:08.910243429Z   File "/opt/render/project/src/backend/config/wsgi.py", line 16, in <module>
2025-07-23T14:41:08.910246139Z     application = get_wsgi_application()
2025-07-23T14:41:08.910248949Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
2025-07-23T14:41:08.910251669Z     django.setup(set_prefix=False)
2025-07-23T14:41:08.910254209Z     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
2025-07-23T14:41:08.910256929Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/__init__.py", line 24, in setup
2025-07-23T14:41:08.910259619Z     apps.populate(settings.INSTALLED_APPS)
2025-07-23T14:41:08.910262169Z     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
2025-07-23T14:41:08.910264749Z   File "/opt/render/project/src/.venv/lib/python3.13/site-packages/django/apps/registry.py", line 124, in populate
2025-07-23T14:41:08.91026733Z     app_config.ready()
2025-07-23T14:41:08.91026999Z     ~~~~~~~~~~~~~~~~^^
2025-07-23T14:41:08.91027277Z   File "/opt/render/project/src/backend/ai_service/apps.py", line 11, in ready
2025-07-23T14:41:08.91027615Z     from . import signals
2025-07-23T14:41:08.91027851Z   File "/opt/render/project/src/backend/ai_service/signals.py", line 7, in <module>
2025-07-23T14:41:08.91028135Z     from ai_services.common.signals import ai_usage_logged
2025-07-23T14:41:08.91029277Z ModuleNotFoundError: No module named 'ai_services'